### ISSUE TITLE
Make basic camera movement

### ISSUE THREAD

**Issue by reaver** [larsivsi/project_peril#4]
Use wasd to move camera position.
Arrow keys to rotate camera.

**Comment by larsivsi** [comment]
Fixed by b8dc7d231fe4feff9998f6dcaee7c5e0a26edea5, 2d78c59ffcc2844e7db3ea12dff0e7f588aab8b3, b6eb8d555ac318cad160efabe90506c7efdb1165 and 8465571f59e5c7dbc4552dacad4d109754fd5a01.
