### ISSUE TITLE
Fix eyedir in phong shaders

### ISSUE THREAD

**Issue by larsivsi** [larsivsi/project_peril#6]
Atm, eyedir is calculated by negating and normalizing lightpos in worldspace. This only works when camera is in (0,0,0).
Therefore, do this calculation in viewspace instead, so that we can move the camera. This implies passing the viewmatrix the shader to convert the lightpos from world to view.

**Comment by reaver** [comment]
Have pushed a fix. Open again if not properly done.

**Comment by larsivsi** [comment]
Fixed by b5d6579903fae780d8b3fbb787c3463f95842533 and eca9813dd996dbe04c99f97f6d0aa408f53c477c
